/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_qiujuer_lame_Lame */

#ifndef _Included_net_qiujuer_lame_Lame
#define _Included_net_qiujuer_lame_Lame
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_qiujuer_lame_Lame
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_qiujuer_lame_Lame_close
  (JNIEnv *, jobject);

/*
 * Class:     net_qiujuer_lame_Lame
 * Method:    encodeMono
 * Signature: ([SI[B)I
 */
JNIEXPORT jint JNICALL Java_net_qiujuer_lame_Lame_encodeMono
  (JNIEnv *, jobject, jshortArray, jint, jbyteArray);

/*
 * Class:     net_qiujuer_lame_Lame
 * Method:    encodeStereo
 * Signature: ([S[SI[B)I
 */
JNIEXPORT jint JNICALL Java_net_qiujuer_lame_Lame_encodeStereo
  (JNIEnv *, jobject, jshortArray, jshortArray, jint, jbyteArray);

/*
 * Class:     net_qiujuer_lame_Lame
 * Method:    flush
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_net_qiujuer_lame_Lame_flush
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     net_qiujuer_lame_Lame
 * Method:    init
 * Signature: (IIIII)V
 */
JNIEXPORT void JNICALL Java_net_qiujuer_lame_Lame_init
  (JNIEnv *, jobject, jint, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
